{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "papermc.fullname" . }}
  labels:
    {{- include "papermc.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.ingress.spec | nindent 2 }}
{{- end }}
