---
name: DCO Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  dco:
    name: Developer Certificate of Origin
    runs-on: ubuntu-latest
    steps:
      - name: Get PR commits
        id: get-pr-commits
        uses: tim-actions/get-pr-commits@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: DCO check
        uses: tim-actions/dco@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commits: ${{ steps.get-pr-commits.outputs.commits }}
