name: Update Docker Hub Description

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
  workflow_dispatch: # Allow manual triggers

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: lexfrei/papermc
          short-description: "Optimized PaperMC Minecraft server Docker image with RCON and health check"
          enable-url-completion: true
